PREFIX abox: <http://bbn.com/synbio/sd2/abox#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX opil: <http://bbn.com/synbio/opil#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sbo: <http://biomodels.net/SBO/> 
PREFIX sbol: <http://sbols.org/v3#>
PREFIX timeseries: <http://bbn.com/synbio/sd2/timeseries#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select ?value ?unitName  where {{
    <{iri}> opil:measurement ?meas .
    ?meas opil:time ?time .
    ?time om:hasNumericalValue ?value ;
          om:hasUnit ?unit .
     ?unit rdfs:label ?unitName . 
	 FILTER (lang(?unitName) = 'en')
}}