PREFIX abox: <http://bbn.com/synbio/sd2/abox#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX opil: <http://bioprotocols.org/opil/v1#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sbo: <http://biomodels.net/SBO/> 
PREFIX sbol: <http://sbols.org/v3#>
PREFIX timeseries: <http://bbn.com/synbio/sd2/timeseries#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select ?paramName ?value ?numericalValue ?unitName where {
    ?paramValue a opil:ParameterValue ;
    		 opil:valueOf ?param.
    ?param opil:name ?paramName.
    OPTIONAL {
          ?paramValue opil:value ?value .
    }
    OPTIONAL {
          ?paramValue opil:hasValueObject ?meas .
          ?meas om:hasNumericalValue ?numericalValue .
          ?meas om:hasUnit ?unit .
          ?unit rdfs:label ?unitName .
          FILTER (lang(?unitName) = 'en')
    }
}
